// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctqwcixnkimwiqpprdjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0cXdjaXhua2ltd2lxcHByZGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjMxNjgsImV4cCI6MjA2NjA5OTE2OH0.3-07kNwlJHpPH45LZqqfbOCo95HVzaVuJlkLPiL-Hhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);